# Generated by Django 5.0 on 2023-12-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('former', models.CharField(max_length=60)),
                ('hours', models.IntegerField()),
                ('first_lesson', models.DateTimeField()),
            ],
        ),
    ]
