# Generated by Django 5.0 on 2023-12-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='note',
            field=models.FloatField(default=10.0),
        ),
    ]
